const data = {
  products: [
    {
      id: 1,
      title: "Mercedes S450",
      image: "https://i.xeoto.com.vn/auto/w250/mercedes/s450/mercedes-s450-2020.png",
      price: 1000,
      company: "Mercedes-Benz",
      info: "This is A-Sedan Class ....",
      inCart: false,
      count: 1,
    },
    {
      id: 2,
      title: "Mercedes GLB 200",
      image: "https://i.xeoto.com.vn/auto/w250/mercedes/glc-300/mercedes-glc-300-2020-59746.png",
      price: 10,
      company: "Mercedes-Benz",
      info: "This is A-Sedan Class ....",
      inCart: false,
      count: 1,
    },
    {
      id: 3,
      title: "Mercedes-Benz E300",
      image: "https://i.xeoto.com.vn/auto/w250/mercedes/gls-450/mercedes-gls-450-2021-99828.png",
      price: 10,
      company: "Mercedes-Benz",
      info: "This is A-Sedan Class ....",
      inCart: false,
      count: 1,
    },
    {
      id: 4,
      title: "Mercedes-Benz E300",
      image: "https://i.xeoto.com.vn/auto/w250/mercedes/e180/mercedes-e180-2021.png",
      price: 10,
      company: "Mercedes-Benz",
      info: "This is A-Sedan Class ....",
      inCart: false,
      count: 1,
    },
    {
      id: 5,
      title: "Mercedes-Benz E300",
      image: "https://i.xeoto.com.vn/auto/w250/mercedes/glb-200/mercedes-glb-200-2021.png",
      price: 10,
      company: "Mercedes-Benz",
      info: "This is A-Sedan Class ....",
      inCart: false,
      count: 1,
    },
    {
      id: 6,
      title: "Mercedes-Benz E300",
      image: "https://i.xeoto.com.vn/auto/w250/mercedes/glb-250/mercedes-glb-250-2021-53259.png",
      price: 10,
      company: "Mercedes-Benz",
      info: "This is A-Sedan Class ....",
      inCart: false,
      count: 1,
    },
    {
      id: 7,
      title: "Mercedes-Benz E300",
      image: "https://m.media-amazon.com/images/I/61tW+ilBQTL._UY560_.jpg",
      price: 10,
      company: "Mercedes-Benz",
      info: "This is A-Sedan Class ....",
      inCart: false,
      count: 1,
    },
    {
      id: 8,
      title: "Mercedes-Benz E300",
      image: "https://i.xeoto.com.vn/auto/w250/mercedes/gls-400/mercedes-gls-400-2020-53392.png",
      price: 10,
      company: "Mercedes-Benz",
      info: "This is A-Sedan Class ....",
      inCart: false,
      count: 1,
    },
    {
      id: 9,
      title: "Mercedes-Benz E300",
      image: "https://i.xeoto.com.vn/auto/w250/mercedes/gls-350d/mercedes-gls-350d-2020-76167.png",
      price: 10,
      company: "Mercedes-Benz",
      info: "This is A-Sedan Class ....",
      inCart: false,
      count: 1,
    },
  ],
};

export default data;
